;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	kill-sexp
	org-self-insert-command
	sgml-slash
	sp-backward-delete-char
	sp-delete-char
	))

(setq mc/cmds-to-run-once
      '(
	delete-region
	sp--self-insert-command
	sp-backward-kill-sexp
	sp-backward-kill-word
	))
